export const jsonUpdatePatient = {
	documentType: 1,
	document: '32760006',
	firstName: 'rosmery',
	otherNames: '',
	lastName: 'arrieta',
	secondSurname: '',
	gender: 'female',
	birthDate: '1970-09-02',
	homeAddress: '',
	email: '6nuew@gmail.com',
	cityId: null,
	homephone: '',
	cellphone: '3506233632',
	whatsapp: '3506233632',
	bloodType: '',
	maritalStatus: '',
	provinceId: null,
	contracts: [
		{
			attGroupId: 36,
			attGroupName: 'Pos Prueba 16 dic',
			companyTypeId: '6',
			companyTypeName: 'Particular',
			companyTypeTag: 'particular',
			contractDescription: 'pRUEBA',
			contractId: 221,
			contractName: 'Particular TTN',
			corporateClient: 'Particular',
			corporateClientId: 150,
			crtId: null,
			crtName: '',
			isEnabled: 1,
			isMain: 0,
			policy: '',
			population: 'particular',
			populationId: 93,
			relId: 1056,
			wsValidated: 0,
		},
		{
			attGroupId: 36,
			attGroupName: 'Pos Prueba 16 dic',
			companyTypeId: '2',
			companyTypeName: 'EPS',
			companyTypeTag: 'eps',
			contractDescription: 'prueba',
			contractId: 245,
			contractName: 'Prueba sura 29',
			corporateClient: 'EPS SURA - PRUEBA',
			corporateClientId: 161,
			crtId: 16,
			crtName: 'A',
			isEnabled: 1,
			isMain: 1,
			policy: '',
			population: '2448 - IPS CALLE 30',
			populationId: 129,
			relId: 1057,
			wsValidated: 1,
		},
	],
	affiliationType: '',
	affiliationTypeId: 2,
	affiliationTypeName: 'Beneficiario',
	address_zone: '',
	age: '53',
	alert: '',
	alertId: null,
	cityName: '',
	docType: 'C.C',
	docTypeId: 1,
	emergencyContact: '',
	id: 749,
	neighborhood: '',
	notes_num: 0,
	ocupation: '',
	provinceName: '',
	urlPhoto: '',
	use_contact_lens: 'No',
	use_glasses: 'No',
	webscrapperValidated: 1,
	eaccount: 129,
};
